apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vol-claim
spec:
  storageClassName: manual
  accessModes:
   - ReadWriteOnce
  volumeName: redis-cache
  resources:
    requests:
      storage: 100Mi