apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-cache
  labels:
    type: local
spec:
  capacity:
   storage: 100Mi
  accessModes:
   - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: "/mnt/data"

